### ISSUE TITLE
Método vazio

### ISSUE THREAD

**Issue by osmarbraz** [gpganis/Emprestimo_Ferramentas#15]
Olhe o método da classe src/main/java/visao/FrmCadastroEmprestimo.java

Não faz nada!

private void JTFAmigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFAmigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFAmigoActionPerformed

**Comment by gpganis** [comment]
👍
